### ISSUE TITLE
undefined method `strip!' for nil:NilClass

### ISSUE THREAD

**Issue by goldmann** [awestruct/awestruct#183]
Ouch, after update from 0.4.5 to 0.4.7.

```
Using profile: development
Generating site: http://localhost:4242
undefined method `strip!' for nil:NilClass
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:167:in `block (2 levels) in load!'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:165:in `lines'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:165:in `each'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:165:in `block in load!'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:164:in `open'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/dependencies.rb:164:in `load!'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/engine.rb:237:in `generate_page'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/engine.rb:220:in `block in generate_output'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/engine.rb:215:in `each'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/engine.rb:215:in `generate_output'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/engine.rb:59:in `run'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/cli/generate.rb:19:in `run'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/cli/invoker.rb:97:in `invoke_generate'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/lib/awestruct/cli/invoker.rb:41:in `invoke!'
/home/goldmann/.gem/ruby/1.9.1/gems/awestruct-0.4.7/bin/awestruct:9:in `<top (required)>'
/usr/bin/awestruct:19:in `load'
/usr/bin/awestruct:19:in `<main>'
>> Thin web server (v1.4.1 codename Chromeo)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:4242, CTRL+C to stop
```
