### ISSUE TITLE
Awestruct 2.0.0 does not work with Listen 2.0

### ISSUE THREAD

**Issue by brianm** [awestruct/awestruct#373]
Listen 2.0 was released and is not backwards compat to 1.3.1, either need to change how it is used, or add a specific version in Gemfile (1.3.1)

```
/Users/brianm/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/awestruct-0.5.3/lib/awestruct/cli/auto.rb:22:in `run': undefined method `change' for #<Listen::Listener:0x007ffdce0882b0> (NoMethodError)
    from /Users/brianm/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/awestruct-0.5.3/lib/awestruct/cli/invoker.rb:120:in `invoke_auto'
    from /Users/brianm/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/awestruct-0.5.3/lib/awestruct/cli/invoker.rb:50:in `invoke!'
    from /Users/brianm/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/awestruct-0.5.3/bin/awestruct:9:in `<top (required)>'
    from /Users/brianm/.rbenv/versions/2.0.0-p0/bin/awestruct:23:in `load'
    from /Users/brianm/.rbenv/versions/2.0.0-p0/bin/awestruct:23:in `<main>'
```
