### ISSUE TITLE
Running awestruct with ruby 2.2 fails because guard is not 'required'

### ISSUE THREAD

**Issue by tristantarrant** [awestruct/awestruct#506]
When starting awestruct with Ruby 2.2 I get the following:

undefined method `init' for Guard:Module
/var/lib/gems/2.2.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/auto.rb:21:in `run'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:144:in `invoke_auto'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:53:in `invoke!'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7.RC2/bin/awestruct:9:in `<top (required)>'
/usr/local/bin/awestruct:23:in `load'
/usr/local/bin/awestruct:23:in `<main>'

This is because 'guard' is never explicitly 'required' but implied transitively by guard/livereload which makes it work in 2.1 but not in 2.2 which I guess is more strict.
